name: adminplacements
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.2.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  firebase_auth: ^0.16.0
  google_sign_in: ^4.4.4

  fluttertoast: ^4.0.1
  firebase_database: ^3.1.5
  firebase_storage: ^3.1.5
  connectivity: ^0.4.8+6
  app_settings: 4.0.0
  file_picker: ^1.9.0+1

  flutter_spinkit: ^4.1.2+1
  flutter_offline: ^0.3.0

  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/
